### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by welchbj** [jinnyyan/monopoly#4]
Hey there, I'm having trouble installing this on my Raspberry Pi. Is this a supported platform?

**Comment by jinnyyan** [comment]
@welchbj Requires unzipping Data.rar to a folder before it can be run. After that, it is compatible with all current Windows/Mac platforms. Have not tested on Raspberry Pi but would recommend you use your primary machine instead.

**Comment by jinnyyan** [comment]
@
